# 创建ndarray
array函数是创建数组最常用的方法，它可以接受一切序列型对象

In [2]:
#设置ast_node_interactivity = "all"使得可以同时输出多条语句
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import numpy as np
lst=[1,2,3,4,5,6]
arr=np.array(lst)
arr

array([1, 2, 3, 4, 5, 6])

如果传入的是一个嵌套序列，则会生成一个多维数组

In [4]:
lst2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(lst2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

可以用属性ndim和shape来查看数组维度和大小

In [5]:
arr2.ndim

2

In [6]:
arr2.shape

(2, 4)

zeros可以创建指定长度或形状的全0数组；ones可以创建指定长度或形状的全1数组；empty可以创建一个空数组，其实empty返回的值不为空，而是一些未初始化的无用值

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
np.empty((2,2))

array([[2.12083484e-316, 3.09391800e+169],
       [3.29216432e+180, 7.20535013e+159]])

arange是内置函数range的数组版

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# ndarray的数据类型

In [13]:
arr=np.array([1,2,3,4])
arr.dtype

dtype('int32')

可以使用astype方法将一个dtype转换为另一个dtype

In [17]:
arr2=arr.astype('float64')
arr2
arr2.dtype

array([1., 2., 3., 4., 5., 6.])

dtype('float64')

In [18]:
arr=np.array([2.35,-1.24,5.6,7.89])
arr2=arr.astype('int32')
arr2
arr2.dtype

array([ 2, -1,  5,  7])

dtype('int32')

# numpy数组运算
数组运算是矢量化的，即任何大小相同的数组之间的算术运算都会应用到元素级

In [19]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [21]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

数组与标量之间的运算，会将标量值传递到各个元素

In [22]:
arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [23]:
arr**2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

大小相同的数组之间的比较会返回布尔值

In [24]:
arr2=np.array([[0,5,2],[5,7,2]])
arr2

array([[0, 5, 2],
       [5, 7, 2]])

In [25]:
arr>arr2

array([[ True, False,  True],
       [False, False,  True]])

# 基本的索引和切片
一维数组的索引和切片很简单，表面上看与python列表功能差不多

In [3]:
arr=np.arange(10)
arr
arr[5]
arr[0:4]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

5

array([0, 1, 2, 3])

如果将一个标量赋值给一个切片，该值会自动传播到整个选取

In [6]:
arr[2:4]=10
arr

array([ 0,  1, 10, 10,  4,  5,  6,  7,  8,  9])

数组切片是原始数组的视图，进行切片操作时，数据不会被复制，视图上的任何修改都会直接反应到原始数组

In [7]:
arr_slice=arr[6:9]
arr_slice
arr_slice[1]=20
arr

array([6, 7, 8])

array([ 0,  1, 10, 10,  4,  5,  6, 20,  8,  9])

在一个二维数组中，各索引位置上的元素不再是标量而是一维数组：

In [9]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d
arr2d[1]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([4, 5, 6])

下面两种方式都可以实现对单个元素的访问

In [10]:
arr2d[1][2]

6

In [11]:
arr2d[1,2]

6

# 布尔型索引
来看下面一个例子

In [15]:
names=np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
arr=np.random.randn(7,4)
arr

array([[-1.02197823,  1.21720834,  0.27761603, -0.93482037],
       [ 0.25254789,  1.61240114,  0.9505209 ,  1.44873647],
       [-0.75655689,  0.15717835, -0.05696867, -0.31221565],
       [-1.55492509, -1.4622513 ,  0.13032184, -1.61900502],
       [-0.02114606, -0.18960953, -0.37777727, -0.32163376],
       [ 0.92888248,  0.83547269, -0.57920036, -0.16688399],
       [-0.82710138,  1.125758  , -0.77206333,  0.96213859]])

假设每个名字都对应arr数组中的一行，而我们想要选出对应于名字"Bob"的所有行。跟算术运算一样，数组的比较运算（如==）也是矢量化的。因此，对names和字符串"Bob"的比较运算将会产生一个布尔型数组：

In [16]:
names=='Bob'
arr[names=='Bob']

array([ True, False, False,  True, False, False, False])

array([[-1.02197823,  1.21720834,  0.27761603, -0.93482037],
       [-1.55492509, -1.4622513 ,  0.13032184, -1.61900502]])

布尔型数组的长度必须跟被索引的轴长度一致。此外，还可以将布尔型数组跟切片、整数（或整数序列，稍后将对此进行详细讲解）混合使用：

In [17]:
arr[names=='Bob',0:2]

array([[-1.02197823,  1.21720834],
       [-1.55492509, -1.4622513 ]])

可以通过以下方式将负值设为零

In [19]:
arr[arr<0]=0
arr

array([[0.        , 1.21720834, 0.27761603, 0.        ],
       [0.25254789, 1.61240114, 0.9505209 , 1.44873647],
       [0.        , 0.15717835, 0.        , 0.        ],
       [0.        , 0.        , 0.13032184, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.92888248, 0.83547269, 0.        , 0.        ],
       [0.        , 1.125758  , 0.        , 0.96213859]])

# 通用函数：快速的元素级数组函数
通用函数（即ufunc）是一种对ndarray中的数据执行元素级运算的函数。你可以将其看做简单函数（接受一个或多个标量值，并产生一个或多个标量值）的矢量化包装器。

In [20]:
arr=np.arange(10)
arr
np.sqrt(arr)
np.exp(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

另外一些（如add或maximum）接受2个数组（因此也叫二元（binary）ufunc），并返回一个结果数组：

In [21]:
x=np.random.randn(5)
y=np.random.randn(5)
x
y
np.maximum(x,y)

array([-0.50458778, -0.69596115,  0.58116756, -1.38643941, -0.93607381])

array([-0.31028623, -0.02410186, -0.17197813,  1.04099781, -1.08956619])

array([-0.31028623, -0.02410186,  0.58116756,  1.04099781, -0.93607381])

有些ufunc的确可以返回多个数组。modf就是一个例子，它是Python内置函数divmod的矢量化版本，它会返回浮点数数组的小数和整数部分：

In [22]:
arr=np.random.randn(5)*10
x,y=np.modf(arr)
arr
x
y

array([ 8.91711482,  3.32113557,  1.45740757, -5.88475096, -4.63546317])

array([ 0.91711482,  0.32113557,  0.45740757, -0.88475096, -0.63546317])

array([ 8.,  3.,  1., -5., -4.])

# 数学和统计方法
可以通过数组上的一组数学函数对整个数组或某个轴向的数据进行统计计算。sum、mean以及标准差std等聚合计算（aggregation，通常叫做约简（reduction））既可以当做数组的实例方法调用，也可以当做顶级NumPy函数使用。

In [4]:
arr=np.random.randn(5,4)
arr

array([[-0.7774939 , -0.09464023, -1.6488254 ,  0.56704453],
       [-0.73421296, -1.50972832,  1.12891206, -0.70742483],
       [ 0.92971247,  1.31428012, -0.29356499,  1.02262086],
       [ 0.16799972,  0.93099657,  0.15274129, -1.03623446],
       [ 0.66749198,  0.72998191,  0.49298922,  1.18913583]])

In [5]:
arr.sum()

2.4917814723826379

In [6]:
arr.mean()
np.mean(arr)

0.12458907361913189

0.12458907361913189

mean和sum这类的函数可以接受一个axis选项参数，用于计算该轴向上的统计值，最终结果是一个少一维的数组，下面arr.mean(axis=1)是计算行的均值，np.mean(arr,axis=0)是计算列的均值

In [11]:
arr.mean(axis=1)
np.mean(arr,axis=0)

array([-0.48847875, -0.45561351,  0.74326211,  0.05387578,  0.76989973])

array([ 0.05069946,  0.27417801, -0.03354956,  0.20702839])

其他如cumsum和cumprod之类的方法则不聚合，而是产生一个由中间结果组成的数组：

In [16]:
arr=np.arange(1,5)
arr
arr.cumsum()
arr.cumprod()

array([1, 2, 3, 4])

array([ 1,  3,  6, 10])

array([ 1,  2,  6, 24])

# 用于布尔型数组的方法
布尔值会被强制转换为1（True）和0（False）。因此，sum经常被用来对布尔型数组中的True值计数：

In [17]:
arr=np.random.randn(20)
arr
(arr>0).sum()

array([ 1.05921615, -0.35392989, -1.27334299,  1.10364841, -0.89913387,
       -0.3349108 , -0.13480325, -0.29097039, -0.47573365,  0.32559478,
        0.54696863,  0.86356712,  1.24371246, -1.22328529,  1.98338124,
        0.48654632, -0.92370343, -0.11923005, -0.27550279,  2.02390119])

9

另外还有两个方法any和all，它们对布尔型数组非常有用。any用于测试数组中是否存在一个或多个True，而all则检查数组中所有值是否都是True：

In [18]:
bools=np.array([True,False,False,False])
bools.any()
bools.all()

True

False

# 排序
跟Python内置的列表类型一样，NumPy数组也可以通过sort方法就地排序：

In [20]:
arr=np.random.randn(10)
arr
arr.sort()
arr

array([ 0.60524879,  0.90762917, -0.05765599,  1.26455787, -0.15667048,
        0.96028414, -1.1890395 ,  1.22468864, -2.80111095, -1.67654787])

array([-2.80111095, -1.67654787, -1.1890395 , -0.15667048, -0.05765599,
        0.60524879,  0.90762917,  0.96028414,  1.22468864,  1.26455787])

多维数组可以在任何一个轴向上进行排序，只需将轴编号传给sort即可：

In [21]:
arr=np.random.randn(4,3)
arr

array([[-0.65881508, -0.01677482, -2.05136771],
       [-0.56562336, -1.3698728 ,  1.53543564],
       [-0.04577827,  1.19481312,  0.83783914],
       [-0.27296963,  2.15384601, -1.00633005]])

In [23]:
arr.sort(axis=0)
arr

array([[-0.65881508, -1.3698728 , -2.05136771],
       [-0.56562336, -0.01677482, -1.00633005],
       [-0.27296963,  1.19481312,  0.83783914],
       [-0.04577827,  2.15384601,  1.53543564]])

# 唯一化以及其它的集合逻辑
NumPy提供了一些针对一维ndarray的基本集合运算。最常用的可能要数np.unique了，它用于找出数组中的唯一值并返回已排序的结果：

In [24]:
arr=np.array([3,3,2,2,4,5,6,5])
np.unique(arr)

array([2, 3, 4, 5, 6])

另一个函数np.in1d用于测试一个数组中的值在另一个数组中的成员资格，返回一个布尔型数组：

In [25]:
values=np.array([2,3,4,5,6])
np.in1d(values,[2,4,5])

array([ True, False,  True,  True, False], dtype=bool)